ad_list = {
    "history": [
        {"data": "images/history/001.png", "attributes": ["crafts", "travel", "movies"]},
        {"data": "images/history/002.png", "attributes": ["cooking", "sports", "animals"]},
        {"data": "images/history/003.png", "attributes": ["travel", "science", "crafts"]},
        {"data": "images/history/004.png", "attributes": ["writing", "fitness", "history"]},
        {"data": "images/history/005.png", "attributes": ["animals", "science", "history"]},
    ],
    "travel": [
        {"data": "images/travel/001.png", "attributes": ["movies", "travel", "history"]},
        {"data": "images/travel/002.png", "attributes": ["crafts", "animals"]},
        {"data": "images/travel/003.png", "attributes": ["science", "animals", "cooking"]},
        {"data": "images/travel/004.png", "attributes": ["writing", "cooking", "travel"]},
        {"data": "images/travel/005.png", "attributes": ["fitness", "science", "animals"]},
    ],
    "cooking": [
        {"data": "images/cooking/001.png", "attributes": ["travel", "crafts", "history"]},
        {"data": "images/cooking/002.png", "attributes": ["crafts", "animals", "movies"]},
        {"data": "images/cooking/003.png", "attributes": ["science", "animals", "travel"]},
        {"data": "images/cooking/004.png", "attributes": ["fitness", "writing", "cooking"]},
        {"data": "images/cooking/005.png", "attributes": ["science", "animals", "travel"]},
    ],
    "crafts": [
        {"data": "images/crafts/001.png", "attributes": ["crafts", "travel", "history"]},
        {"data": "images/crafts/002.png", "attributes": ["animals", "movies", "cooking"]},
        {"data": "images/crafts/003.png", "attributes": ["science", "travel", "animals"]},
        {"data": "images/crafts/004.png", "attributes": ["fitness", "travel", "writing"]},
        {"data": "images/crafts/005.png", "attributes": ["animals", "science", "sports"]},
    ],
    "science": [
        {"data": "images/science/001.png", "attributes": ["crafts", "travel", "animals"]},
        {"data": "images/science/002.png", "attributes": ["cooking", "animals", "movies"]},
        {"data": "images/science/003.png", "attributes": ["travel", "science", "animals"]},
        {"data": "images/science/004.png", "attributes": ["fitness", "writing", "history"]},
        {"data": "images/science/005.png", "attributes": ["crafts", "animals", "history"]},
    ],
    "animals": [
        {"data": "images/animals/001.png", "attributes": ["travel", "crafts", "history"]},
        {"data": "images/animals/002.png", "attributes": ["crafts", "movies", "cooking"]},
        {"data": "images/animals/003.png", "attributes": ["travel", "science", "animals"]},
        {"data": "images/animals/004.png", "attributes": ["fitness", "writing", "history"]},
        {"data": "images/animals/005.png", "attributes": ["science", "animals", "crafts"]},
    ],
    "fitness": [
        {"data": "images/fitness/001.png", "attributes": ["crafts", "travel", "writing"]},
        {"data": "images/fitness/002.png", "attributes": ["animals", "cooking", "movies"]},
        {"data": "images/fitness/003.png", "attributes": ["travel", "science", "animals"]},
        {"data": "images/fitness/004.png", "attributes": ["history", "animals", "writing"]},
        {"data": "images/fitness/005.png", "attributes": ["crafts", "cooking", "science"]},
    ],
    "writing": [
        {"data": "images/writing/001.png", "attributes": ["crafts", "travel", "history"]},
        {"data": "images/writing/002.png", "attributes": ["animals", "movies", "cooking"]},
        {"data": "images/writing/003.png", "attributes": ["animals", "travel", "science"]},
        {"data": "images/writing/004.png", "attributes": ["fitness", "animals", "cooking"]},
        {"data": "images/writing/005.png", "attributes": ["science", "crafts", "fitness"]},
    ],
    "movies": [
        {"data": "images/movies/001.png", "attributes": ["crafts", "travel", "history"]},
        {"data": "images/movies/002.png", "attributes": ["cooking", "animals", "sports"]},
        {"data": "images/movies/003.png", "attributes": ["travel", "crafts", "science"]},
        {"data": "images/movies/004.png", "attributes": ["fitness", "writing", "crafts"]},
        {"data": "images/movies/005.png", "attributes": ["science", "animals", "history"]},
    ],
    "sports": [
        {"data": "images/sports/001.png", "attributes": ["travel", "crafts", "history"]},
        {"data": "images/sports/002.png", "attributes": ["cooking", "animals", "movies"]},
        {"data": "images/sports/003.png", "attributes": ["travel", "science", "animals"]},
        {"data": "images/sports/004.png", "attributes": ["fitness", "writing", "cooking"]},
        {"data": "images/sports/005.png", "attributes": ["animals", "science", "writing"]},
    ],
}